import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Utilities/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Warkop Cashier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 left-0 flex flex-col h-screen w-12 items-center border-r border-neutral-600/40 bg-neutral-900">
          <Navbar />
        </div>
        <div className="ml-12 min-h-screen bg-neutral-900 text-neutral-300">{children}</div>
      </body>
    </html>
  );
}
